### ISSUE TITLE
Fixing the url 

### ISSUE THREAD

**Issue by meeravaria** [DMU-CTEC2902-1920/MMsq#24]
Can you fix the url http://localhost:52806/ErrorHandler/NotFound?aspxerrorpath=/Views/User/Index.cshtml as when you run it, it comes up with an error message

**Comment by mathunila** [comment]
> Can you fix the url http://localhost:52806/ErrorHandler/NotFound?aspxerrorpath=/Views/User/Index.cshtml as when you run it, it comes up with an error message

Currently working on this issue but not sure when this will be resolved hopefully within the next few days of debugging.

**Comment by mqasim212** [comment]
That's fine. Once sorted give us a heads up.

Thanks
