### ISSUE TITLE
Changing images

### ISSUE THREAD

**Issue by meeravaria** [DMU-CTEC2902-1920/MMsq#25]
In the home page, can mati change the images resolution and pixel to make clearer.

**Comment by mathunila** [comment]
**I am working on that right now :)** @meeravaria

**Comment by meeravaria** [comment]
Thanks. Could you also add an overlay

**Comment by mathunila** [comment]
> Thanks. Could you also add an overlay - @mathunila

I have resolved this issue! Please check the Dev Branch for the result :) @meeravaria @mqasim212

**Comment by meeravaria** [comment]
very good work guys :)

**Comment by meeravaria** [comment]
> > Thanks. Could you also add an overlay - @mathunila
> 
> I have resolved this issue! Please check the Dev Branch for the result :) @meeravaria @mqasim212

very good work guys :)
