### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by mqasim212** [DMU-CTEC2902-1920/MMsq#29]
Add a search bar to the home page that is placed in an appropriate place where it can be easily accessed.

**Comment by mathunila** [comment]
> Add a search bar to the home page that is placed in an appropriate place where it can be easily accessed.

I will inform Sufiyaan to get this issue resolve today.

**Comment by meeravaria** [comment]
> > Add a search bar to the home page that is placed in an appropriate place where it can be easily accessed.
> 
> I will inform Sufiyaan to get this issue resolve today.

Ok thank you!
