### ISSUE TITLE
Adding links

### ISSUE THREAD

**Issue by meeravaria** [DMU-CTEC2902-1920/MMsq#31]
Can you add links to the images in the home page redirecting them to the specific page required :)

**Comment by mathunila** [comment]
> Can you add links to the images in the home page redirecting them to the specific page required :)

I will start on this issue now! 👍 @meeravaria

**Comment by SufiyaanTH** [comment]
> Can you add links to the images in the home page redirecting them to the specific page required :)
> 
> I will start on this issue now! 👍 @meeravaria

Updated the links to the images on the home page and edited the footer so it redirects to its relevant web pages
