### ISSUE TITLE
Under construction pages 

### ISSUE THREAD

**Issue by meeravaria** [DMU-CTEC2902-1920/MMsq#32]
Can you create the under construction pages for privacy policy, terms and conditions and code of conduct. Thanks @SufiyaanTH

**Comment by mathunila** [comment]
> Can you create the under construction pages for the privacy policy, terms and conditions and code of conduct. Thanks @SufiyaanTH

I'll try to get the page up and running as soon as possible. Hopefully today!  @meeravaria

**Comment by meeravaria** [comment]
> > Can you create the under construction pages for the privacy policy, terms and conditions and code of conduct. Thanks @SufiyaanTH
> 
> I'll try to get the page up and running as soon as possible. Hopefully today! @meeravaria

Thank you 👍

**Comment by SufiyaanTH** [comment]
I have created the under construction pages. Can you have a look? @mathunila @meeravaria @mqasim212 and let me know if anything needs changing? if not, the issue can be closed!
