### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by meeravaria** [DMU-CTEC2902-1920/MMsq#36]
Can you guys start adding comments to each section of code so we know which code is for what. 
 Thank you 
@SufiyaanTH @mathunila

**Comment by mathunila** [comment]
> Can you guys start adding comments to each section of code so we know which code is for what.
> Thank you
> @SufiyaanTH @mathunila

I will start adding comments on all the pages that we have created so far. @meeravaria

**Comment by mathunila** [comment]
I've added comments on all relevant pages. This issue is now resolved! @meeravaria @SufiyaanTH
