### ISSUE TITLE
Update Documentations

### ISSUE THREAD

**Issue by mathunila** [DMU-CTEC2902-1920/MMsq#41]
Hi Meera and Qasim, 

Could you please update the current documentation especially the class diagrams, test plans, and screen designs? 

@meeravaria @mqasim212 
Regards, 
Mati

**Comment by meeravaria** [comment]
> Hi Meera and Qasim,
> 
> Could you please update the current documentation especially the class diagrams, test plans, and screen designs?
> 
> @meeravaria @mqasim212
> Regards,
> Mati

Already on it 👍

**Comment by mqasim212** [comment]
Yes sure. Can you push your work to github so i can view the updated pages.

**Comment by meeravaria** [comment]
> Hi Meera and Qasim,
> 
> Could you please update the current documentation especially the class diagrams, test plans, and screen designs?
> 
> @meeravaria @mqasim212
> Regards,
> Mati

Completed the UML, Test Plan and Use Case up to date until further changes are required

**Comment by mqasim212** [comment]
The test plan and screen designs have been completed and updated.
