### ISSUE TITLE
Other pages

### ISSUE THREAD

**Issue by meeravaria** [DMU-CTEC2902-1920/MMsq#43]
Please complete the following pages by Tuesday
 
- Game Review
- Developers Page
- Developers Page (Admin page)
- League Table
- FAQ
- Login (Admin page)
- Login (User page)

**Comment by mathunila** [comment]
working on it @meeravaria 
completed pages: 
- HOME 
- ABOUT 
- CONTACT US

**Comment by mathunila** [comment]
Completed FAQ/Help and Terms and Conditions pages! @meeravaria

**Comment by meeravaria** [comment]
> working on it @meeravaria
> completed pages:
> 
> * HOME
> * ABOUT
> * CONTACT US

Can you now start on:
developers page, @SufiyaanTH  
league table, @mathunila or @SufiyaanTH 
login (admin), @mathunila 
login (users), @mathunila 
and game review  @SufiyaanTH

**Comment by meeravaria** [comment]
What is the update on the latest? - @mathunila @SufiyaanTH
