### ISSUE TITLE
Contact Us and About MMSQ

### ISSUE THREAD

**Issue by meeravaria** [DMU-CTEC2902-1920/MMsq#49]
On the **contact us** and **about mmsq** pages the social media tags aren't in the right place, can you place them in the middle of the footer like the rest of the pages - @mathunila  @SufiyaanTH

**Comment by mathunila** [comment]
I have positioned the footer tags in the center and this is structured the same throughout the entire website. @meeravaria

**Comment by meeravaria** [comment]
> I have positioned the footer tags in the center and this is structured the same throughout the entire website. @meeravaria

Perfect
