### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by meeravaria** [DMU-CTEC2902-1920/MMsq#50]
Can you make the text a bigger and move to the middle of page - @mathunila @SufiyaanTH

**Comment by mathunila** [comment]
> Can you make the text a bigger and move to the middle of page - @mathunila @SufiyaanTH

I have completed this issue now. Could you please have a look at it? @meeravaria

**Comment by meeravaria** [comment]
> > Can you make the text a bigger and move to the middle of page - @mathunila @SufiyaanTH
> 
> I have completed this issue now. Could you please have a look at it? @meeravaria

Yes that's fine thanks
